# Generated by Django 5.1 on 2024-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsetgoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecategory',
            old_name='vehicle_category',
            new_name='vehiclecategory',
        ),
    ]
