# Generated by Django 5.1 on 2024-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsetgoapp', '0002_rename_vehicle_category_vehiclecategory_vehiclecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
    ]
