# Generated by Django 5.1 on 2024-09-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsetgoapp', '0003_booking_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_name',
        ),
    ]
