# Generated by Django 5.1 on 2024-09-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsetgoapp', '0004_remove_booking_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
