# Generated by Django 5.1 on 2024-09-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsetgoapp', '0008_rename_name_vehiclecategory_cname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecategory',
            old_name='cname',
            new_name='name',
        ),
    ]
