# Generated by Django 5.1 on 2024-09-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsetgoapp', '0009_rename_cname_vehiclecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
