# Generated by Django 5.1 on 2024-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsetgoapp', '0010_alter_vehiclecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
